server:
  port: 8082

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: user-service

  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: users
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  jwt:
    secret: ${JWT_SECRET}
  gateway:
    secret: ${GATEWAY_SECRET}
  security:
    public-routes: []
  wallet:
    signup-bonus: 100.00
