apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: readoracontainerregistry.azurecr.io/readora-ai-service
  newName: readoracontainerregistry.azurecr.io/readora-ai-service
  newTag: 7750359d22dad1ba2d1ab65d2685c8906297940f
