# Independent kustomization for just commerce-service — requires `kubectl apply -k k8s/shared` first.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: readoracontainerregistry.azurecr.io/readora-commerce-service
  newName: readoracontainerregistry.azurecr.io/readora-commerce-service
  newTag: 09645ca819131bf3a145ba89359b686955bb60d3
