server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: auth-service

  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth
    show-sql: true

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-ttl-minutes: 15
    refresh-token-ttl-days: 30
  security:
    max-failed-login-attempts: 5
  gateway:
    secret: ${GATEWAY_SECRET}