# Independent kustomization for just notification-service — requires `kubectl apply -k k8s/shared` first.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: readoracontainerregistry.azurecr.io/readora-notification-service
  newName: readoracontainerregistry.azurecr.io/readora-notification-service
  newTag: 374387b2e4b00da02528cd88b6d7e6ae7cc7986a
