# Independent kustomization for just notification-service — requires `kubectl apply -k k8s/shared` first.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: readoracontainerregistry.azurecr.io/readora-notification-service
  newName: readoracontainerregistry.azurecr.io/readora-notification-service
  newTag: f7c092a7f64a7cb569981018638a11fd87900961
