# Independent kustomization for just api-gateway — requires `kubectl apply -k k8s/shared` first.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: readoracontainerregistry.azurecr.io/readora-api-gateway
  newName: readoracontainerregistry.azurecr.io/readora-api-gateway
  newTag: c305505c1e51e830a97bb967963e81ae933086d1
