apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: readoracontainerregistry.azurecr.io/readora-frontend-user
  newName: readoracontainerregistry.azurecr.io/readora-frontend-user
  newTag: 84d6eeaf68f41484d196a814bf13d1db2094f616
