# Independent kustomization for just delivery-agent-service — requires `kubectl apply -k k8s/shared` first.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: readoracontainerregistry.azurecr.io/readora-delivery-agent-service
  newName: readoracontainerregistry.azurecr.io/readora-delivery-agent-service
  newTag: 09cb6f41620320cd028eb8ff6e941b603264ae7a
