package com.readora.commerce.repository;

import com.readora.commerce.entity.DeliveryType;
import com.readora.commerce.entity.Order;
import com.readora.commerce.entity.OrderStatus;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.dao.DataIntegrityViolationException;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.math.BigDecimal;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * The real value here: every OrderStatus in the return workflow actually persists against
 * Postgres's raw CHECK constraint on the status column — a typo in that constraint (added by
 * hand in the V1 baseline SQL, not generated by Hibernate) would show up here, never in a
 * Mockito-backed unit test.
 */
@Testcontainers
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class OrderRepositoryIT {

    @Container
    @ServiceConnection
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:18-alpine");

    @Autowired
    private OrderRepository orderRepository;

    @Autowired
    private TestEntityManager entityManager;

    private Order newOrder(String idempotencyKey) {
        return new Order(
                "ORD-" + UUID.randomUUID(), UUID.randomUUID(), "INR", new BigDecimal("500.00"), BigDecimal.ZERO,
                BigDecimal.ZERO, BigDecimal.ZERO, new BigDecimal("500.00"), BigDecimal.ZERO, "WALLET", idempotencyKey, DeliveryType.PHYSICAL
        );
    }

    @Test
    void returnWorkflow_everyStatusIsAcceptedByTheRealCheckConstraint() {
        Order order = orderRepository.saveAndFlush(newOrder("checkout:" + UUID.randomUUID()));

        order.markDelivered();
        orderRepository.saveAndFlush(order);

        order.requestReturn("damaged in transit");
        orderRepository.saveAndFlush(order);

        order.approveReturn();
        orderRepository.saveAndFlush(order);

        order.assignReturnAgent(UUID.randomUUID(), "Pickup Agent");
        orderRepository.saveAndFlush(order);

        order.markReturnEnRoute();
        orderRepository.saveAndFlush(order);

        order.markReturnCollected();
        orderRepository.saveAndFlush(order);

        order.initiateRefund();
        orderRepository.saveAndFlush(order);

        order.completeReturn();
        orderRepository.saveAndFlush(order);
        entityManager.clear();

        Order reloaded = orderRepository.findById(order.getId()).orElseThrow();
        assertThat(reloaded.getStatus()).isEqualTo(OrderStatus.RETURNED);
    }

    @Test
    void duplicateIdempotencyKey_violatesTheRealUniqueConstraint() {
        String idempotencyKey = "checkout:" + UUID.randomUUID();
        orderRepository.saveAndFlush(newOrder(idempotencyKey));

        assertThatThrownBy(() -> orderRepository.saveAndFlush(newOrder(idempotencyKey)))
                .isInstanceOf(DataIntegrityViolationException.class);
    }
}
