apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: readoracontainerregistry.azurecr.io/readora-auth-service
  newName: readoracontainerregistry.azurecr.io/readora-auth-service
  newTag: 5db96adc314b17a3c966ccdecab641a81ca0df90
