# Independent kustomization for just frontend-user — requires `kubectl apply -k k8s/shared` first.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: readoracontainerregistry.azurecr.io/readora-frontend-user
  newName: readoracontainerregistry.azurecr.io/readora-frontend-user
  newTag: 00c144fbbf47b201b46fa43a922a9860a29615bc
