apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: readoracontainerregistry.azurecr.io/readora-api-gateway
  newName: readoracontainerregistry.azurecr.io/readora-api-gateway
  newTag: 95841cbff856fe0ee6a453b823c56e77a13e33e0
