# Independent kustomization for just catalog-service — requires `kubectl apply -k k8s/shared` first.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: readoracontainerregistry.azurecr.io/readora-catalog-service
  newName: readoracontainerregistry.azurecr.io/readora-catalog-service
  newTag: 209a35fad760fd289d7f5dbdff9c2565ea059186
