server:
  port: 8086

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: notification-service

  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: notifications
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  jwt:
    secret: ${JWT_SECRET}
  gateway:
    secret: ${GATEWAY_SECRET}
  security:
    public-routes: []
