apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: readoracontainerregistry.azurecr.io/readora-catalog-service
  newName: readoracontainerregistry.azurecr.io/readora-catalog-service
  newTag: 48b3df514bbfaa7a5f8e3ebaf4a62db767379f7c
