# Independent kustomization for just frontend-admin — requires `kubectl apply -k k8s/shared` first.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: readoracontainerregistry.azurecr.io/readora-frontend-admin
  newName: readoracontainerregistry.azurecr.io/readora-frontend-admin
  newTag: 5f473445b1a6fb55469963d7684ec26eb8dfc260
