# Independent kustomization for just frontend-admin — requires `kubectl apply -k k8s/shared` first.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: readoracontainerregistry.azurecr.io/readora-frontend-admin
  newName: readoracontainerregistry.azurecr.io/readora-frontend-admin
  newTag: a83de96edf04c351112407cdf360f088a91eefad
